baseurl: /sam-web-design-standards

# Markdown config
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
# highlighter: rouge

name: Draft SAM Web Design Standards

source: /

version: 0.1.0

exclude:
- go
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- CONTRIBUTING.md
- ".sass-cache"
- ".ruby-version"
- vendor
- node_modules

permalink: pretty

repos:
- name: Draft SAM Web Design Standards
  description: Main repository for the Draft U.S. Web Design Standards
  url: https://github.com/jbrucegsa/sam-web-design-standards
# - name: Draft SAM Web Design Standards Assets
#   description: Draft SAM Web Design Standards visual design assets
#   url: https://github.com/jbrucegsa/sam-web-design-standards-assets

# google_analytics_ua: UA-48605964-33

sass:
  sass_dir: _scss
#  style: :compressed

collections:
  visual:
    output: true
    permalink: /:path/
  layout-system:
    output: true
    permalink: /:path/
  elements:
    output: true
    permalink: /:path/
  components:
    output: true
    permalink: /:path/
  form-controls:
    output: true
    permalink: /form-controls/:path/
  form-templates:
    output: true
    permalink: /form-templates/:path/
  other:
    output: true
    permalink: /other/:path/
  search:
    output: true
    permalink: /search/:path/

